version: "3"
services:
  web:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "4200:80"
    depends_on:
      - api
  api:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - AWS_REGION=$AWS_REGION
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - DATABASE_HOST=$DB_HOST
      - DATABASE_PORT=$DB_PORT
      - DATABASE_USER=$DB_USERNAME
      - DATABASE_PASSWORD=$DB_PASSWORD
      - DATABASE_NAME=$DB_NAME
      - LOCALSTACK_HOSTNAME=localstack
    depends_on:
      - db
      - localstack
  db:
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8081:80"
    depends_on:
      - db
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3,ses
    ports:
      - "4572:4572"
      - "4579:4579"
volumes:
  db_data:
